import fs from 'fs'
import metadata from '@solar-icons/core/metadata.json' assert { type: 'json' }

const toPascalCase = (str: string) =>
    str
        .split('-')
        .map(word => word.charAt(0).toUpperCase() + word.slice(1))
        .join('')

const outputFilePath = './components/home-page/sections/hero/generatedHeroUtils.ts'
const categoryList: string[] = []

const generateIconsByCategory = (data: any) => {
    const categories = data.categories
    let output = `
/* Generated by generateUtils.ts */
import { solar } from '@solar-icons/react'

export const styles = ['Broken', 'Outline', 'Linear', 'Bold', 'LineDuotone', 'BoldDuotone'] as const
export type Style = (typeof styles)[number]

export const getIconsByCategory = (category: string) => {
  switch (category) {
`

    Object.entries(categories).forEach(([categoryName, categoryData]: [string, any]) => {
        const icons = categoryData.icons

        // Vérifie qu'il y a au moins 23 icônes pour la catégorie
        if (icons.length < 23) return
        const categoryPascalCase = toPascalCase(categoryName)
        categoryList.push(categoryPascalCase)
        // Sépare les icônes en interne (10) et externe (13)
        const innerIcons = icons
            .slice(0, 10)
            .map((icon: string) => `solar.${categoryPascalCase}.${toPascalCase(icon)}`)
        const outerIcons = icons
            .slice(10, 23)
            .map((icon: string) => `solar.${categoryPascalCase}.${toPascalCase(icon)}`)

        // Génère le code TypeScript pour chaque catégorie
        output += `
    case '${categoryPascalCase}':
      return {
        inner: [
          ${innerIcons.join(',\n          ')}
        ],
        outer: [
          ${outerIcons.join(',\n          ')}
        ],
      };
`
    })

    // Termine le switch et exporte la fonction par défaut
    output += `
    default:
      return {
        inner: [],
        outer: [],
      };
  }
}
`
    // add categories as exported const array
    output += `export const categories = ${JSON.stringify(categoryList)} as const\n`

    // export Category type based on categories
    output += 'export type Category = typeof categories[number]'

    return output
}

// Fonction principale pour lire le fichier JSON et écrire le fichier TypeScript généré
const main = async () => {
    try {
        const outputContent = generateIconsByCategory(metadata)
        fs.writeFileSync(outputFilePath, outputContent)
        console.log('Le fichier TypeScript a été généré avec succès !')
    } catch (error) {
        console.error('Erreur lors de la génération du fichier :', error)
    }
}

main()
