name: 'Install'
description: 'Sets up Node.js and runs install'
inputs:
    node-version:
        description: 'Version de Node.js'
        required: true
        default: '20.11'

runs:
    using: composite
    steps:
        - name: Install dependencies
          uses: pnpm/action-setup@v4

        - name: Set up Node.js ${{ inputs.node-version }}
          uses: actions/setup-node@v4
          with:
              node-version: ${{ inputs.node-version }}
              registry-url: 'https://registry.npmjs.org'
              cache: 'pnpm'

        - name: Setup Git User
          shell: bash
          run: |
              git config --global user.email "saoudihakim@gmail.com"
              git config --global user.name "Hakim Saoudi"

        - name: Install dependencies
          shell: bash
          run: pnpm install
